#!/usr/bin/env sh
if [ "$3" != "" ]; then
  DETECTED_ENV="$3"
else
  DETECTED_ENV="production"
fi

case "$DETECTED_ENV" in
  "production") ;;
  *) echo "Unsupported environment $DETECTED_ENV"
    exit 2
    ;;
esac

CHEF_ENV="$DETECTED_ENV" bundle exec knife solo data bag "$1" "$2" "$DETECTED_ENV"
