#!/usr/bin/env sh
if [ "$2" != "" ]; then
  DETECTED_ENV="$2"
else
  DETECTED_ENV="production"
fi

case "$DETECTED_ENV" in
  "production") FQDN_SERVER="server.volgactf.org";;
  *) echo "Unsupported environment $DETECTED_ENV"
    exit 2
    ;;
esac
bundle exec knife solo prepare "$1.$FQDN_SERVER"
